# tasks file for ansible/roles/create_network

- name: Create network
  community.docker.docker_network:
    name: app-database-network

- name: Create app-proxy network
  community.docker.docker_network:
    name: app-proxy-network

- name: Create proxy to front network
  docker_network:
    name: app-front-network