# tasks file for ansible/roles/create_network

- name: Create network
  community.docker.docker_network:
    name: my-network

- name: Create app-proxy network
  community.docker.docker_network:
    name: app-proxy-network