---
# tasks file for ansible/roles/launch_proxy

- name: Run HTTPD
  community.docker.docker_container:
    name: httpd
    image: "wanoni/tp-devops-httpd:latest"
    networks:
      - name: app-network
    ports:
      - 8050:80
