# tasks file for ansible/roles/launch_proxy

- name: Run HTTPD
  community.docker.docker_container:
    name: httpd
    image: "wanoni/tp-devops-httpd:latest"
    pull: yes
    networks:
      - name: app-proxy-network
    ports:
      - "80:80"
      - "8080:8080"