---
# tasks file for ansible/roles/launch_proxy

- name: Launch Proxy Container
  community.docker.docker_container:
    name: http-server
    image: evlacy/tp-devops-httpd:latest
    pull: yes
    networks:
      - name: app-database-network
      - name: appn-front-network
    ports:
      - "80:80"
      - "8080:8080"