---
# tasks file for ansible/roles/launch_app

- name: Launch Application Container
  community.docker.docker_container:
    name: simple-api
    image: wanoni/tp-devops-simple-api:latest
    pull: yes
    env_file: /.env
    networks:
      - name: app-database-network
      - name: app-proxy-network