# tasks file for ansible/roles/launch_app

- name: Run Simple API
  community.docker.docker_container:
    name: simple-api
    image: "wanoni/tp-devops-simple-api:latest"
    pull: yes
    networks:
      - name: my-network
      - name: app-proxy-network
      - name: app-front-network
    env:
      DATABASE_HOST: "{{ DATABASE_HOST }}"
      DATABASE_PASSWORD: "{{ DATABASE_PASSWORD }}"