# tasks file for ansible/roles/launch_app

- name: Run Simple API
  community.docker.docker_container:
    name: simple-api
    image: "wanoni/tp-devops-simple-api:latest"
    networks:
      - name: my-network
    env:
      DATABASE_HOST: "postgres"
      DATABASE_PASSWORD: "pwd"