---
# tasks file for ansible/roles/launch_database

- name: Run Postgres
  community.docker.docker_container:
    name: postgres
    image: wanoni/tp-devops-database:latest
    pull: yes
    env_file: /home/admin/.env
    networks:
      - name: app-database-network
    container_default_behavior: compatibility
    networks_cli_compatible: no
    volumes:
      - db-volume:/var/lib/postgresql/data