---
# tasks file for ansible/roles/launch_database

- name: Launch Database Container
  community.docker.docker_container:
    name: database
    image: wanoni/tp-devops-database:latest
    pull: yes
    env_file: /.env
    networks:
      - name: app-database-network
    volumes:
      - db-volume:/var/lib/postgresql/data