# tasks file for ansible/roles/launch_database

- name: Run Postgres
  community.docker.docker_container:
    name: postgres
    image: "wanoni/tp-devops-database:latest"
    pull: yes
    networks:
      - name: app-database-network
    env:
      POSTGRES_DB: "{{ POSTGRES_DB }}"
      POSTGRES_USER: "{{ POSTGRES_USER }}"
      POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
    volumes:
      - db-volume:/var/lib/postgresql/data