- hosts: all
  gather_facts: true
  become: true

  vars_files:
    - token.yml

  roles:
    - docker
    - create_network
    - launch_database
    - launch_app
    - launch_proxy
    - launch_front
    