name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["Test Backend"]
    types:
      - completed
    branches: 
      - main
    pull_request:
      branches:
        - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main' # Ensure deploy only runs for main
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get version tag
        id: get_version
        run: echo ::set-output name=version::$(date +%Y%m%d%H%M%S)

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v3
        with:
          context: ./simple-api  # Chemin vers le Dockerfile de l’API
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          push: true

      - name: Build and Push Database Image
        uses: docker/build-push-action@v3
        with:
          context: ./database  # Chemin vers le Dockerfile de la BDD
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          push: true

      - name: Build and Push HTTP Server Image
        uses: docker/build-push-action@v3
        with:
          context: ./http-server  # Chemin vers le Dockerfile du serveur HTTP
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          push: true
